# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm ci
          npm test
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout $CI_COMMIT_REF_NAME
          SPACE_CHAR=" "
          npx standard-version --releaseCommitMessageFormat "chore(release):${SPACE_CHAR}{{currentTag}} [skip ci]" -t "${TAG_PREFIX}"
          git push --follow-tags origin $CI_COMMIT_REF_NAME

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          git pull -f
          npm config list
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_NODE_AUTH_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          git pull -f
          npm login --registry=https://npm.pkg.github.com/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
